name: Akcja CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Uruchom moją własną akcję kontenerową
        uses: ./
        with:
          who-to-greet: "@gesiud"
