name: Akcja CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Uruchom moją własną akcję kontenerową
        id: my-action
        uses: ./
        with:
          who-to-greet: "@gesiud"

      - name: Output the answer
        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"

      - name: Test the container
        if: ${{ steps.my-action.outputs.answer != 42}}
        run: |
          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer is not expected"
